### ISSUE TITLE
Handling of acoustic cells with no single targets

### ISSUE THREAD

**Issue by dmwarn** [JVAdams/EchoNet2Fish#2]
Early on I was under the impression that the estimateACMT() function populated cells with Sv data but no single target data (no frequency distribution data at all due to lack of targets) with a zero.  

In trying to diagnose some issues that were not related at all I found that my belief was wrong.  I don't think this is consistent with the original SAS code from which some of this was derived.  

This has no impact on whole-water column density at an given interval but will have an impact if one is exploring the vertical distribution of fish in interval-layer data.

Example image of a transect (so2) from Lake Michigan plotted from one of the outputs from estimateACMT(), intlaymeans_nph.csv.

![image](https://user-images.githubusercontent.com/7394862/36946482-8dff9a0c-1f8b-11e8-84f3-a83696e3755a.png)

**Comment by JVAdams** [comment]
Thanks for catching this.  The estimateACMT() function has been replaced with the new estimateLake() function, and this function now populates cells with Sv data but no single target data with zeroes.
