### ISSUE TITLE
estimateLake() save of 

### ISSUE THREAD

**Issue by dmwarn** [JVAdams/EchoNet2Fish#4]
This is not really an issue but rather a request. It would be great if estimateLake() saved the "svts5" data.frame to the "L# Y#### Estimates.RData" file. 

I know a user can get this on their own with some tweaks though.

**Comment by JVAdams** [comment]
New version 0.3.2 includes data frame svts5 in output as both an object in the Rdata file and a csv file.

svts5 = the result of merging the SV and TS data, with several changes made: subsetted to valid regions, original and modified sigma estimates of n1, nv, fish_ha, depth_botmid (bottom depth range), and identity of slice, nearmt (nearest midwater trawl), region, and region area.
